FROM ubuntu:16.04

COPY ./mvs_build /opt/mvs_build

RUN cd /opt/mvs_build && /bin/bash build_metaverse_image.sh

VOLUME [~/.metaverse]

# P2P Network
EXPOSE 5251
# JSON-RPC CALL
EXPOSE 8820
# Websocket notifcations
EXPOSE 8821

ENTRYPOINT ["/usr/local/bin/mvsd"]
